version: '3.1'
services:
  app:
    container_name: sapp
    image: sapp-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ds33h9jb3q
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sapp
      
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    hostname: localhost
#    volumes:
#      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    depends_on:
#      - prometheus
#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins
#    ports:
#      - "7070:8080"

