version: '3.1'
services:
  app:
    container_name: sapp
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8086:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sapp
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: localhost
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus