apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digitalocean-prod
spec:
  acme:
    # PLEASE CHANGE IT
    email: patronix.systems@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: patronix-prod-issuer-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-token
              key: TOKEN
        selector:
          dnsZones:
            - "patronix-systems.com"
