provider: digitalocean
logLevel: debug
domainFilters:
  - patronix-systems.com
env:
  - name: DO_TOKEN
    valueFrom:
      secretKeyRef:
        name: digitalocean-token
        key: TOKEN
