apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sapp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: sapp.local  # Update this line
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sapp
                port:
                  number: 8080
