apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-stage
spec:
  acme:
    # PLEASE CHANGE IT
    email: patronix.systems@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: patronix-issuer-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: cloudflare-token
              key: TOKEN
        selector:
          dnsZones:
            - "patronix-systems.org"