apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sapp
spec:
  minReplicas: 3
  maxReplicas: 12
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 30
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sapp
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60