apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sapp-app
  annotations:
    cert-manager.io/cluster-issuer: digitalocean-prod
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: sapp.patronix-systems.org
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sapp-app
                port:
                  number: 80
  tls:
    - hosts:
        - sapp.patronix-systems.org
      secretName: sapp-app-ingress