apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapp-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sapp-app
  template:
    metadata:
      labels:
        app: sapp-app
    spec:
      containers:
        - name: sapp-app
          image: patronix9345/sapp-app:v1.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
          env:
            - name: POSTGRES_HOST
              value: postgresql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 0
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: patronix9345/postgres:v1.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: sapp
