apiVersion: v1
kind: Service
metadata:
  name: sapp-app
spec:
  selector:
    app: sapp-app
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432