apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 31000
      targetPort: 31000
    - name: jnlp
      protocol: TCP
      port: 50000
      targetPort: 50000
