apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 31000
    targetPort: 31000
  - protocol: TCP
    port: 50000
    targetPort: 50000