apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc  # Specify a name for your PVC
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode as needed
  resources:
    requests:
      storage: 10Gi  # Adjust storage size as needed