apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 31000
      nodePort: 31000
  type: NodePort