apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: sapp
  namespace: default
roleRef:
  kind: ClusterRole 
  name: view
  apiGroup: rbac.authorization.k8s.io